input_type: "mesh"
in_out: True
augment_on_the_fly: False
mesh_jitter: False
dataset_folder: "/data_ssd/pwojcik/sh_raw_train/"
wandb_dir: .
batch_size: 2048
lr: 1e-2
model_type: siren
bayesian: False
logging_root: './logs'
shape_modify: 'no'
exp_name: "snr_cars_overfitting"
steps_til_summary: 100
epochs_til_ckpt: 1
hidden_features: 128
kl_weight: 0
epochs: 5000
scheduler:
  type: adaptive
  step_size: 30
  gamma: 0.1
  min_lr: 1e-5
  patience: 50
  patience_adaptive: 10
  factor: 0.8
  threshold: 0
multi_process:
  enabled: False
  part_id: 0
  n_of_parts: 4
  first_weights_name:
  ignore_first: False
n_points: 100000
is_meta: True
strategy: first_weights
clip_grad: False
mlp_config:
  in_features: 2
  out_features: 3
  hidden_features: 128
  hidden_layers: 3
  outermost_linear: True